# Generated by Django 5.2.6 on 2025-09-10 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uptimee", "0002_task_verificationcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
